In [1]:
import import_ipynb
import myfunc
import MyModels
import pandas as pd
import numpy as np

importing Jupyter notebook from myfunc.ipynb
importing Jupyter notebook from MyModels.ipynb


In [2]:
data = myfunc.read_file("data_sample.xlsx")

In [3]:
len(data)

108212

In [4]:
ch1 = myfunc.remove_url(myfunc.split_all_sentence(data["Text"]))

In [5]:
ch2 = myfunc.change(ch1)

In [6]:
new_text = []
for test1 in ch2:
    s1= []
    for test2 in test1.split():
        if test2 != " ":
            s1.append(test2)
    new_text.append(" ".join(s1))

In [7]:
Label = data["Label"]
data1 = pd.DataFrame({"Text": new_text, "Label":Label})

In [8]:
data_after = data1.drop_duplicates(["Text"],keep = "last")
print(len(data))
print(len(data_after))

108212
99243


In [9]:
import MeCab

def kimchi(text, custom_list = ["NNP","NNG","VV","VA","XR", "UNKNOWN"]):
    tagger = MeCab.Tagger()
    real = tagger.parse(text)
    separate_text = real.split()
    real_text = separate_text[:-1]
    words = []
    types = []
    ans2 = []
    selected_words = []
    
    for i in range(len(real_text)):
        if i%2 == 0:
            words.append(real_text[i])
        else:
            types.append(real_text[i].split(",")[0])        
    ans = list(zip(words, types))
       
    if custom_list == []:
        ans2 = " ".join(words)
        #ans2 = words
    
    else:
        for i in ans:
            if i[1] in custom_list:
                selected_words.append(i[0])
                
        ans2 = " ".join(selected_words)
        #ans2 = selected_words
    return ans2

In [10]:
test = data_after["Text"][0:1][0]
test_1 = kimchi(test)
print(test_1)

사람 모르 유명 하 일본 편의점 음식 일본 미니스톱 아이스 果 세상 사람 먹 ㅠ유유ㅠㅠㅠ 위 바닐라 아이스 밑 딸기 연유


In [11]:
m = data_after["Text"]
new_mor = []
for text in m:
    morpheme = kimchi(text)
    new_mor.append(morpheme)

In [12]:
new_mor[0:2]

['사람 모르 유명 하 일본 편의점 음식 일본 미니스톱 아이스 果 세상 사람 먹 ㅠ유유ㅠㅠㅠ 위 바닐라 아이스 밑 딸기 연유',
 '아이스 오락 시간 아이스 오락 시간 아이스 유연 왕']

In [13]:
new_text1 = myfunc.decompose_text(new_mor)
new_text2 = myfunc.remove_alpha(new_text1)

In [14]:
new_text2[0]

'ㅅㅏㄹㅏㅁ ㅁㅗㄹㅡ ㅇㅠㅁㅕㅇ ㅎㅏ ㅇㅣㄹㅂㅗㄴ ㅍㅕㄴㅇㅢㅈㅓㅁ ㅇㅡㅁㅅㅣㄱ ㅇㅣㄹㅂㅗㄴ ㅁㅣㄴㅣㅅㅡㅌㅗㅂ ㅇㅏㅇㅣㅅㅡ  ㅅㅔㅅㅏㅇ ㅅㅏㄹㅏㅁ ㅁㅓㄱ ㅠㅇㅠㅇㅠㅠㅠㅠ ㅇㅟ ㅂㅏㄴㅣㄹㄹㅏ ㅇㅏㅇㅣㅅㅡ ㅁㅣㅌ ㄸㅏㄹㄱㅣ ㅇㅕㄴㅇㅠ'

In [15]:
Label = data_after["Label"]
data_after_2 = pd.DataFrame({"Text": new_text2, "Label":Label})

In [16]:
data_after_2.head()

Text  Label
0  ㅅㅏㄹㅏㅁ ㅁㅗㄹㅡ ㅇㅠㅁㅕㅇ ㅎㅏ ㅇㅣㄹㅂㅗㄴ ㅍㅕㄴㅇㅢㅈㅓㅁ ㅇㅡㅁㅅㅣㄱ ㅇㅣㄹ...      0
1  ㅇㅏㅇㅣㅅㅡ ㅇㅗㄹㅏㄱ ㅅㅣㄱㅏㄴ ㅇㅏㅇㅣㅅㅡ ㅇㅗㄹㅏㄱ ㅅㅣㄱㅏㄴ ㅇㅏㅇㅣㅅㅡ ㅇ...      0
2    ㅇㅗㄹㅐㅅㅁㅏㄴ ㅇㅏㅇㅣㅅㅡ ㄷㅗㄹㅊㅔ ㄹㅏㄸㅔ ㅁㅏㅅㅇㅣㅆ ㅂㅜㅅㅏㄴㄱㅘㅇㅇㅕㄱㅅㅣ      0
3  ㅁㅏㅅㅈㅣㅂ ㅌㅏㅁㅎㅓㅁㄷㅐ ㄴㅗㄹㄹㅏ ㅋㅓㅍㅣ ㅌㅔㄹㅏ ㄴㅏㄹㅆㅣ ㄴㅐㅇㅋㅓㅍㅣ ...      0
4  ㄹㅔㄱㅅㅡ ㅇㅏㅇㅣㅅㅡ ㄷㅏㅇㅣㅇㅏ ㄱㅗ ㅈㅠㅇㅓㄹㄹㅣ ㅁㅕㅇㅍㅜㅁ ㅅㅣㄱㅖ ㄱㅡㅁ...      0

In [17]:
## 개인적으로 확인해볼 내용
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

train_X, test_X, train_Y, test_Y = train_test_split(data_after_2['Text'],data_after_2['Label'],test_size=0.3, random_state = 1)

Tfidf_vect = TfidfVectorizer(max_features = 50000)
Tfidf_vect.fit(train_X[:].values.astype('U'))

Train_X_Tfidf = Tfidf_vect.transform(train_X[:].values.astype('U'))
Test_X_Tfidf = Tfidf_vect.transform(test_X[:].values.astype('U'))

Tfidf_vect = TfidfVectorizer(max_features = 50000)
Tfidf_vect.fit(train_X[:].values.astype('U'))

Train_X_Tfidf = Tfidf_vect.transform(train_X[:].values.astype('U'))
Test_X_Tfidf = Tfidf_vect.transform(test_X[:].values.astype('U'))

In [18]:
print(Train_X_Tfidf.shape)
print(Test_X_Tfidf.shape)
print(Tfidf_vect.get_feature_names())

(69470, 44208)
(29773, 44208)
['ㄱㅏ', 'ㄱㅏㄱ', 'ㄱㅏㄱㄱㅏㄱ', 'ㄱㅏㄱㄱㅗ', 'ㄱㅏㄱㄱㅘㄴ', 'ㄱㅏㄱㄱㅜㅇ', 'ㄱㅏㄱㄷㅐ', 'ㄱㅏㄱㄷㅗ', 'ㄱㅏㄱㄹㅐ', 'ㄱㅏㄱㄹㅕㄱ', 'ㄱㅏㄱㅁㅏ', 'ㄱㅏㄱㅁㅗㄱ', 'ㄱㅏㄱㅂㅏㄱ', 'ㄱㅏㄱㅂㅕㄹ', 'ㄱㅏㄱㅅㅓ', 'ㄱㅏㄱㅅㅓㄹㅇㅣ', 'ㄱㅏㄱㅅㅓㄹㅌㅏㅇ', 'ㄱㅏㄱㅅㅓㅇ', 'ㄱㅏㄱㅅㅓㅇㅈㅔ', 'ㄱㅏㄱㅅㅜ', 'ㄱㅏㄱㅅㅣㅌㅏㄹ', 'ㄱㅏㄱㅇㅏㄴ', 'ㄱㅏㄱㅇㅗ', 'ㄱㅏㄱㅇㅚ', 'ㄱㅏㄱㅇㅣ', 'ㄱㅏㄱㅇㅣㄴ', 'ㄱㅏㄱㅇㅣㄹ', 'ㄱㅏㄱㅈㅏ', 'ㄱㅏㄱㅈㅐ', 'ㄱㅏㄱㅈㅓㄴ', 'ㄱㅏㄱㅈㅗㅇ', 'ㄱㅏㄱㅈㅣ', 'ㄱㅏㄱㅈㅣㄹ', 'ㄱㅏㄱㅊㅓㄴ', 'ㄱㅏㄱㅎㅏ', 'ㄱㅏㄱㅎㅐ', 'ㄱㅏㄱㅎㅐㅇ', 'ㄱㅏㄱㅏ', 'ㄱㅏㄱㅏㅁ', 'ㄱㅏㄱㅏㅁㅔㄹ', 'ㄱㅏㄱㅓ', 'ㄱㅏㄱㅓㄴㅁㅜㄹ', 'ㄱㅏㄱㅔ', 'ㄱㅏㄱㅕㄱ', 'ㄱㅏㄱㅕㄱㄷㅐ', 'ㄱㅏㄱㅕㄱㅍㅛ', 'ㄱㅏㄱㅖ', 'ㄱㅏㄱㅗ', 'ㄱㅏㄱㅗㄱ', 'ㄱㅏㄱㅗㅇ', 'ㄱㅏㄱㅘㄴ', 'ㄱㅏㄱㅜ', 'ㄱㅏㄱㅡㄹㅣㄴ', 'ㄱㅏㄱㅡㅂㅈㅓㄱ', 'ㄱㅏㄱㅣ', 'ㄱㅏㄲㅏㅂ', 'ㄱㅏㄲㅏㅇㅜ', 'ㄱㅏㄲㅏㅇㅝ', 'ㄱㅏㄲㅏㅇㅣ', 'ㄱㅏㄲㅜ', 'ㄱㅏㄳㄴㅣㅁㅇㅢ', 'ㄱㅏㄴ', 'ㄱㅏㄴㄱㅕㄱ', 'ㄱㅏㄴㄱㅕㄹ', 'ㄱㅏㄴㄱㅕㅇ', 'ㄱㅏㄴㄱㅗㄱ', 'ㄱㅏㄴㄱㅗㅈㅣ', 'ㄱㅏㄴㄱㅘ', 'ㄱㅏㄴㄱㅡㄱ', 'ㄱㅏㄴㄱㅣㄴㅡㅇ', 'ㄱㅏㄴㄷㅏㄴ', 'ㄱㅏㄴㄷㅏㅁㅎㅚ', 'ㄱㅏㄴㄷㅏㅇ', 'ㄱㅏㄴㄷㅐ', 'ㄱㅏㄴㄷㅑㅇ', 'ㄱㅏㄴㄷㅓ', 'ㄱㅏㄴㄷㅓㅇㅇㅣ', 'ㄱㅏㄴㄷㅔㅇㅓㅄ', 'ㄱㅏㄴㄸㅐㅇㅇㅣ', 'ㄱㅏㄴㄹㅑㄱ', 'ㄱㅏㄴㅁㅏㄴ', 'ㄱㅏㄴㅂㅏㅁ', 'ㄱㅏㄴㅂㅓㅂ', 'ㄱㅏㄴㅂㅕㅇ', 'ㄱㅏㄴㅂㅜ', 'ㄱㅏㄴㅂㅜㅈㅣㄴ', 'ㄱㅏㄴㅅㅏㅇㅣ', 'ㄱㅏㄴㅅㅓㅂ', 'ㄱㅏㄴㅅㅓㅇ', 'ㄱㅏㄴㅅㅗ', 'ㄱㅏㄴㅅㅜ', 'ㄱㅏㄴㅅㅣㄱ', 'ㄱㅏㄴㅅㅣㄱㄱㅓㄹㅣ', 'ㄱㅏㄴㅈㅏ', 'ㄱㅏㄴㅈㅏㅇ', 'ㄱㅏㄴㅈㅓㄱ', 'ㄱㅏㄴㅈㅓㄹ', 'ㄱㅏㄴㅈㅓㅂ', 'ㄱㅏㄴㅈㅚ

In [19]:
Train_X,Test_X,Train_Y,Test_Y = MyModels.data_transformer(data_after_2)

In [20]:
print(test_Y.shape)

(29773,)


In [21]:
svm = MyModels.learning_svm(Train_X,Train_Y)

In [22]:
svm_predict = MyModels.predict_SVM(svm,Test_X)

In [23]:
print(MyModels.score(svm_predict,Test_Y))

ACCURACY :  99.93618379068283
Precision Score : 0.9863760217983651
Recall Score :  0.9627659574468085
F1 Score :  0.9744279946164199
None


In [24]:
NB = MyModels.learning_MNB(Train_X,Train_Y)

In [25]:
NB_predict = MyModels.predict_MNB(NB,Test_X)

In [26]:
print(MyModels.score(NB_predict,Test_Y))

ACCURACY :  99.62382023981459
Precision Score : 0.9962406015037594
Recall Score :  0.7047872340425532
F1 Score :  0.825545171339564
None


In [27]:
KNN = MyModels.learning_KNN(Train_X, Train_Y)

In [28]:
KNN_predict = MyModels.predict_KNN(KNN, Test_X)

In [29]:
print(MyModels.score(KNN_predict,Test_Y))

ACCURACY :  99.82198636348369
Precision Score : 0.976401179941003
Recall Score :  0.8803191489361702
F1 Score :  0.925874125874126
None


In [30]:
MyModels.show_confusion_matrix(svm_predict,Test_Y)

[[29392     5]
 [   14   362]]


In [31]:
MyModels.show_confusion_matrix(NB_predict,Test_Y)

[[29396     1]
 [  111   265]]


In [32]:
MyModels.show_confusion_matrix(KNN_predict,Test_Y)

[[29389     8]
 [   45   331]]


In [45]:
count = 0
for i in Test_Y:
    #print(i)
    if i == 1:
        count += 1
print(count)

376


In [ ]:
data_after.to_excel("isreal.xlsx")

In [ ]:
"º".isalpha()

[기능 추가할 점]
1. 붙여쓰는 단어들은 따로 라이브러리를 사용하여 나눌 필요가 있음(N >= 10) : 근거 : 제일 긴 낱말이 11자 정도임 (속도는 해봐야...)
2. ㅇㅏㅇㅣㅅㅡ 같은 단어들도 처리할 방법 ㅇㅅㅇ 이나 ㅜㅅㅜ 같은 이모티콘은 자음모음을 합치게 되면 2글자 이상의 단어가 안됨을 이용? 현재는 그냥 일단 다 지우는 방향으로 코드를 작성함
3. 특수문자 처리 : ' 나 , 같은 단어가 처리 안됨을 확인
4. 영어도 지워야 할까?
5. 부족한 마약 판매 게시글 --> 29000 VS 150( 추가적으로 수집)  #수집중
6. 마약 판매 게시글의 특징 : 같은 게시글인데 연락 메신저의 ID만 계속 바꾸는 형식을 취함 --> 영어 삭제의 필요성(4)
7. 어떤 문장이 주어지면 이것이 판매 게시글인지 아닌지 테스트 해 볼 수 있는 프로그램 만들기
8. 앞부분이 같은 문장이 반복되고 뒷부분은 계속 바뀌는 형태 --> 놔둬도 될것같은 느낌.
9. 전처리 순서 생각해보기 --> 단일 글자에 대해 지워지지 않고 남아 있는것을 확인.
10. 수동으로 Threshold를 조절해서 재현율을 증가?
11. 재현율이 떨어지는 원인 : Label이 1인 데이터의 부족이라고 생각함 --> 충분한 학습을 하지 못함

In [ ]:
import MeCab
m = MeCab.Tagger()
out = m.Tagger("wow")
print(out)