In [2]:
import import_ipynb
import myfunc
import MyModels
import pandas as pd
import numpy as np

importing Jupyter notebook from myfunc.ipynb
importing Jupyter notebook from MyModels.ipynb


In [3]:
data = myfunc.read_file("data_sample.xlsx")

In [4]:
len(data)

108212

In [5]:
ch1 = myfunc.remove_url(myfunc.split_all_sentence(data["Text"]))

In [6]:
ch2 = myfunc.change(ch1)

In [7]:
new_text = []
for test1 in ch2:
    s1= []
    for test2 in test1.split():
        if test2 != " ":
            s1.append(test2)
    new_text.append(" ".join(s1))

In [8]:
Label = data["Label"]
del data
data = pd.DataFrame({"Text" : new_text,"Label" : Label})

In [9]:
data_after = data.drop_duplicates(["Text"],keep = "last")
print(len(data))
print(len(data_after))

108212
99243


In [10]:
data_after.head()

Text  Label
0  사람들이 잘 모르는데 진짜 유명해졌으면 하는 일본 편의점 음식 일본 미니스톱 아이스...      0
1             아이스의오락시간 아이스 의 오락시간 과연 누가 아이스의 유연성 왕일지      0
2    오 오랫만에 아이스 돌체라떼 음 맛있겠다 Starbucks in 부산광역시 Busan      0
3  맛집탐험대 나를 놀라게한 커피 TERAROSA TERAROSA 테라로사 날씨 냉커피...      0
4              로렉스 아이스 다이아 고씨쥬얼리 명품시계 금 화이트 골드 화이트골드      0

In [11]:
Train_X,Test_X,Train_Y,Test_Y = MyModels.data_transformer(data_after)

In [26]:
## 개인적으로 확인해볼 내용
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

train_X, test_X, train_Y, test_Y = train_test_split(data_after['Text'],data_after['Label'],test_size=0.3, random_state = 1)

Tfidf_vect = TfidfVectorizer(max_features = 100000)
Tfidf_vect.fit(train_X[:].values.astype('U'))

Train_X_Tfidf = Tfidf_vect.transform(train_X[:].values.astype('U'))
Test_X_Tfidf = Tfidf_vect.transform(test_X[:].values.astype('U'))

Tfidf_vect = TfidfVectorizer(max_features = 100000)
Tfidf_vect.fit(train_X[:].values.astype('U'))

Train_X_Tfidf = Tfidf_vect.transform(train_X[:].values.astype('U'))
Test_X_Tfidf = Tfidf_vect.transform(test_X[:].values.astype('U'))

In [28]:
print(Tfidf_vect.get_feature_names())
print(Train_X_Tfidf.shape)

['aa', 'aaa', 'aafvymiejbnucn', 'aal', 'aa요', 'ab', 'abc', 'abc가', 'abc랑', 'abc초콜렛', 'abijammm', 'abite', 'abko', 'able', 'abo', 'about', 'abroad', 'absolute', 'absolutel', 'abtovo역은', 'abu이며', 'abyrinth', 'ab이브를', 'ab컷에서', 'ab크리스탈', 'ac', 'accessory', 'account', 'ace', 'aceravi', 'achime의', 'achu', 'acistwiting', 'acorn', 'act', 'actions', 'active', 'actor', 'actorleeminho', 'ac가', 'ad', 'add', 'added', 'addidas', 'adicionei', 'adidas', 'adina', 'adj', 'adolescence', 'adonis', 'adorable', 'ae', 'aehwan', 'aerialofficial', 'aesthetic', 'aeternus', 'afamily', 'afc', 'afd', 'affair', 'after', 'afterglow', 'again', 'again은', 'age', 'agency', 'aglet', 'ago', 'agree체크하고', 'ah', 'ahab', 'ahhhhh', 'ahn', 'ai', 'aids', 'ain', 'air', 'airkush', 'airplane', 'ais', 'aitai', 'aiyana', 'ai가', 'aj', 'ajoongkim', 'ajouté', 'ak', 'aka', 'akaashi', 'akaasi', 'akz', 'al', 'albireo', 'album', 'aldk', 'aldks', 'alexandra', 'alisa', 'alive', 'all', 'allen', 'alley', 'allpresso', 'allrisesilver', 'allrt', '

In [12]:
svm = MyModels.learning_svm(Train_X,Train_Y)

In [13]:
svm_predict = MyModels.predict_SVM(svm,Test_X)

In [14]:
print(MyModels.score(svm_predict,Test_Y))

ACCURACY :  99.96641252141202
Precision Score : 1.0
Recall Score :  0.973404255319149
F1 Score :  0.986522911051213
None


In [15]:
NB = MyModels.learning_MNB(Train_X,Train_Y)

In [16]:
NB_predict = MyModels.predict_MNB(NB,Test_X)

In [17]:
print(MyModels.score(NB_predict,Test_Y))

ACCURACY :  99.73465891915494
Precision Score : 1.0
Recall Score :  0.7898936170212766
F1 Score :  0.8826151560178307
None


In [18]:
KNN = MyModels.learning_KNN(Train_X, Train_Y)

In [19]:
KNN_predict = MyModels.predict_KNN(KNN, Test_X)

In [21]:
print(MyModels.score(KNN_predict,Test_Y))

ACCURACY :  99.66076646626138
Precision Score : 1.0
Recall Score :  0.7313829787234043
F1 Score :  0.8448540706605223
None


In [22]:
MyModels.show_confusion_matrix(svm_predict,Test_Y)

[[29397     0]
 [   10   366]]


In [23]:
MyModels.show_confusion_matrix(NB_predict,Test_Y)

[[29397     0]
 [   79   297]]


In [24]:
MyModels.show_confusion_matrix(KNN_predict,Test_Y)

[[29397     0]
 [  101   275]]


In [ ]:
count = 0
for i in Test_Y:
    #print(i)
    if i == 1:
        count += 1
print(count)

In [19]:
data_after.to_excel("isreal.xlsx")

In [24]:
"º".isalpha()

True

[기능 추가할 점]
1. 붙여쓰는 단어들은 따로 라이브러리를 사용하여 나눌 필요가 있음(N >= 10) : 근거 : 제일 긴 낱말이 11자 정도임 (속도는 해봐야...)
2. ㅇㅏㅇㅣㅅㅡ 같은 단어들도 처리할 방법 ㅇㅅㅇ 이나 ㅜㅅㅜ 같은 이모티콘은 자음모음을 합치게 되면 2글자 이상의 단어가 안됨을 이용? 현재는 그냥 일단 다 지우는 방향으로 코드를 작성함
3. 특수문자 처리 : ' 나 , 같은 단어가 처리 안됨을 확인
4. 영어도 지워야 할까?
5. 부족한 마약 판매 게시글 --> 29000 VS 150( 추가적으로 수집)  #수집중
6. 마약 판매 게시글의 특징 : 같은 게시글인데 연락 메신저의 ID만 계속 바꾸는 형식을 취함 --> 영어 삭제의 필요성(4)
7. 어떤 문장이 주어지면 이것이 판매 게시글인지 아닌지 테스트 해 볼 수 있는 프로그램 만들기
8. 앞부분이 같은 문장이 반복되고 뒷부분은 계속 바뀌는 형태 --> 놔둬도 될것같은 느낌.
9. 전처리 순서 생각해보기 --> 단일 글자에 대해 지워지지 않고 남아 있는것을 확인.
10. 수동으로 Threshold를 조절해서 재현율을 증가?
11. 재현율이 떨어지는 원인 : Label이 1인 데이터의 부족이라고 생각함 --> 충분한 학습을 하지 못함

In [ ]:
import MeCab
m = MeCab.Tagger()
out = m.Tagger("wow")
print(out)